// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2UDScD_vj2aLbSKqYeHzF-jr7TJ4nLiQ',
    appId: '1:27484519910:web:94ea53318fca10f5f5aa27',
    messagingSenderId: '27484519910',
    projectId: 'ocronelasttime',
    authDomain: 'ocronelasttime.firebaseapp.com',
    storageBucket: 'ocronelasttime.firebasestorage.app',
    measurementId: 'G-TQXG683VK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrl-CpAJ3fkUw0LHZJmBn3LKTVXvodOj4',
    appId: '1:27484519910:android:3e7fcbfa36bda7d9f5aa27',
    messagingSenderId: '27484519910',
    projectId: 'ocronelasttime',
    storageBucket: 'ocronelasttime.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6D1i3nUfd85viH9KmASCUnH_uwh0FzkE',
    appId: '1:27484519910:ios:ad9e3e190264bb60f5aa27',
    messagingSenderId: '27484519910',
    projectId: 'ocronelasttime',
    storageBucket: 'ocronelasttime.firebasestorage.app',
    iosBundleId: 'com.example.ocr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6D1i3nUfd85viH9KmASCUnH_uwh0FzkE',
    appId: '1:27484519910:ios:ad9e3e190264bb60f5aa27',
    messagingSenderId: '27484519910',
    projectId: 'ocronelasttime',
    storageBucket: 'ocronelasttime.firebasestorage.app',
    iosBundleId: 'com.example.ocr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2UDScD_vj2aLbSKqYeHzF-jr7TJ4nLiQ',
    appId: '1:27484519910:web:d4c458d94547f28df5aa27',
    messagingSenderId: '27484519910',
    projectId: 'ocronelasttime',
    authDomain: 'ocronelasttime.firebaseapp.com',
    storageBucket: 'ocronelasttime.firebasestorage.app',
    measurementId: 'G-11YYW2G9Q7',
  );
}
